name: My workflow
on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello Thomas Routers"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo " bye Thomas"
