name: 03-workflowrunners
on: push

jobs:
    unbuntu-echo:
          runs-on: ubuntu-latest
          steps: 
             - name: Show OS
               run: |
                 echo " This jonb is running on an ubuntu runner"
                 echo " Runner OS: $RUNNER_OS"